from ctypes import DEFAULT_MODE
import os
from dotenv import load_dotenv
from chromadb.config import Settings

load_dotenv()


DEFAULT_PERSIST_DIRECTORY = "db"
PERSIST_DIRECTORY = os.environ.get('PERSIST_DIRECTORY', DEFAULT_PERSIST_DIRECTORY)

DEFAULT_SOURCE_DIRECTORY = "source_documents"
SOURCE_DIRECTORY = os.environ.get('SOURCE_DIRECTORY', DEFAULT_SOURCE_DIRECTORY)

DEFAULT_EMBEDDINGS_MODEL_NAME = "all-MiniLM-L6-v2"
EMBEDDINGS_MODEL_NAME = os.environ.get('EMBEDDINGS_MODEL_NAME',DEFAULT_EMBEDDINGS_MODEL_NAME)

DEFAULT_CHUNK_SIZE = 500
CHUNK_SIZE = int(os.environ.get('CHUNK_SIZE', DEFAULT_CHUNK_SIZE))

DEFAULT_CHUNK_OVERLAP = 50
CHUNK_OVERLAP = int(os.environ.get('CHUNK_OVERLAP', DEFAULT_CHUNK_OVERLAP))

DEFAULT_TARGET_SOURCE_CHUNKS = 4
TARGET_SOURCE_CHUNKS = int(os.environ.get('TARGET_SOURCE_CHUNKS', DEFAULT_TARGET_SOURCE_CHUNKS))

DEFAULT_CHROMA_DB_IMPL = 'duckdb+parquet'
CHROMA_DB_IMPL = os.environ.get('CHROMA_DB_IMPL', DEFAULT_CHROMA_DB_IMPL)

DEFAULT_CHROMA_TELEMETRY = False
CHROMA_TELEMETRY = os.environ.get('CHROMA_TELEMETRY', DEFAULT_CHROMA_TELEMETRY)

DEFAULT_CHROMA_PERSIST_DIRECTORY = DEFAULT_PERSIST_DIRECTORY
CHROMA_PERSIST_DIRECTORY = os.environ.get('CHROMA_PERSIST_DIRECTORY', DEFAULT_CHROMA_PERSIST_DIRECTORY)

CHROMA_SETTINGS = Settings(
        chroma_db_impl=CHROMA_DB_IMPL,
        persist_directory=CHROMA_PERSIST_DIRECTORY,
        anonymized_telemetry=CHROMA_TELEMETRY
)

DEFAULT_MODEL_TYPE = "GPT4All"
MODEL_TYPE = os.environ.get('MODEL_TYPE', DEFAULT_MODEL_TYPE)

DEFAULT_MODEL_PATH = "models/ggml-gpt4all-j-v1.3-groovy.bin"
MODEL_PATH = os.environ.get('MODEL_PATH', DEFAULT_MODEL_PATH)

DEFAULT_MODEL_N_CTX = 1000
MODEL_N_CTX = os.environ.get('MODEL_N_CTX', DEFAULT_MODEL_N_CTX)

