FROM nvidia/cuda:12.1.1-devel-ubuntu22.04
EXPOSE 8080
ENV PORT=8080

# Install everything to build llama.cpp and install it
RUN apt-get update && apt-get upgrade -y \
    && apt-get install -y git build-essential \
    python3 python3-pip gcc wget \
    ocl-icd-opencl-dev opencl-headers clinfo \
    libclblast-dev libopenblas-dev \
    wget \
    && mkdir -p /etc/OpenCL/vendors && echo "libnvidia-opencl.so.1" > /etc/OpenCL/vendors/nvidia.icd

RUN CMAKE_ARGS="-DLLAMA_CUBLAS=on" pip install llama-cpp-python

WORKDIR /app

# Copy dependencies first for better caching
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy everything else
COPY . .
ENTRYPOINT python api/main.py