llm:
  auto_discover_models: false
  default_model: gpt-5.1
embedding:
  auto_discover_models: false
  default_model: text-embedding-ada-002
models:
  - type: llm
    name: gpt-3.5-turbo
    mode: openai
    provider: openai
    enabled: true
    alias: gpt-3.5-turbo
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: gpt-3.5-turbo-16k
    mode: openai
    provider: openai
    enabled: true
    alias: gpt-3.5-turbo-16k
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: gpt-4-0613
    mode: openai
    provider: openai
    enabled: true
    alias: gpt-4-0613
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: gpt-4
    mode: openai
    provider: openai
    enabled: true
    alias: gpt-4
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: gpt-3.5-turbo-1106
    mode: openai
    provider: openai
    enabled: true
    alias: gpt-3.5-turbo-1106
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: gpt-3.5-turbo-0125
    mode: openai
    provider: openai
    enabled: true
    alias: gpt-3.5-turbo-0125
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: gpt-4-turbo
    mode: openai
    provider: openai
    enabled: true
    alias: gpt-4-turbo
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: gpt-4-turbo-2024-04-09
    mode: openai
    provider: openai
    enabled: true
    alias: gpt-4-turbo-2024-04-09
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: gpt-4o
    mode: openai
    provider: openai
    enabled: true
    alias: gpt-4o
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: gpt-4o-2024-05-13
    mode: openai
    provider: openai
    enabled: true
    alias: gpt-4o-2024-05-13
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: gpt-4o-mini-2024-07-18
    mode: openai
    provider: openai
    enabled: true
    alias: gpt-4o-mini-2024-07-18
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: gpt-4o-mini
    mode: openai
    provider: openai
    enabled: true
    alias: gpt-4o-mini
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: gpt-4o-2024-08-06
    mode: openai
    provider: openai
    enabled: true
    alias: gpt-4o-2024-08-06
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: o1-2024-12-17
    mode: openai
    provider: openai
    enabled: true
    alias: o1-2024-12-17
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: o1
    mode: openai
    provider: openai
    enabled: true
    alias: o1
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: o3-mini
    mode: openai
    provider: openai
    enabled: true
    alias: o3-mini
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: o3-mini-2025-01-31
    mode: openai
    provider: openai
    enabled: true
    alias: o3-mini-2025-01-31
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: gpt-4o-2024-11-20
    mode: openai
    provider: openai
    enabled: true
    alias: gpt-4o-2024-11-20
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: o1-pro-2025-03-19
    mode: openai
    provider: openai
    enabled: true
    alias: o1-pro-2025-03-19
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: o1-pro
    mode: openai
    provider: openai
    enabled: true
    alias: o1-pro
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: o3-2025-04-16
    mode: openai
    provider: openai
    enabled: true
    alias: o3-2025-04-16
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: o4-mini-2025-04-16
    mode: openai
    provider: openai
    enabled: true
    alias: o4-mini-2025-04-16
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: o3
    mode: openai
    provider: openai
    enabled: true
    alias: o3
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: o4-mini
    mode: openai
    provider: openai
    enabled: true
    alias: o4-mini
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: gpt-4.1-2025-04-14
    mode: openai
    provider: openai
    enabled: true
    alias: gpt-4.1-2025-04-14
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: gpt-4.1
    mode: openai
    provider: openai
    enabled: true
    alias: gpt-4.1
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: gpt-4.1-mini-2025-04-14
    mode: openai
    provider: openai
    enabled: true
    alias: gpt-4.1-mini-2025-04-14
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: gpt-4.1-mini
    mode: openai
    provider: openai
    enabled: true
    alias: gpt-4.1-mini
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: gpt-4.1-nano-2025-04-14
    mode: openai
    provider: openai
    enabled: true
    alias: gpt-4.1-nano-2025-04-14
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: gpt-4.1-nano
    mode: openai
    provider: openai
    enabled: true
    alias: gpt-4.1-nano
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: o3-pro
    mode: openai
    provider: openai
    enabled: true
    alias: o3-pro
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: o3-pro-2025-06-10
    mode: openai
    provider: openai
    enabled: true
    alias: o3-pro-2025-06-10
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: gpt-5-chat-latest
    mode: openai
    provider: openai
    enabled: true
    alias: gpt-5-chat-latest
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: gpt-5-2025-08-07
    mode: openai
    provider: openai
    enabled: true
    alias: gpt-5-2025-08-07
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: gpt-5
    mode: openai
    provider: openai
    enabled: true
    alias: gpt-5
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: gpt-5-mini-2025-08-07
    mode: openai
    provider: openai
    enabled: true
    alias: gpt-5-mini-2025-08-07
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: gpt-5-mini
    mode: openai
    provider: openai
    enabled: true
    alias: gpt-5-mini
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: gpt-5-nano-2025-08-07
    mode: openai
    provider: openai
    enabled: true
    alias: gpt-5-nano-2025-08-07
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: gpt-5-nano
    mode: openai
    provider: openai
    enabled: true
    alias: gpt-5-nano
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: gpt-5-pro-2025-10-06
    mode: openai
    provider: openai
    enabled: true
    alias: gpt-5-pro-2025-10-06
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: gpt-5-pro
    mode: openai
    provider: openai
    enabled: true
    alias: gpt-5-pro
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: gpt-5.1-chat-latest
    mode: openai
    provider: openai
    enabled: true
    alias: gpt-5.1-chat-latest
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: gpt-5.1-2025-11-13
    mode: openai
    provider: openai
    enabled: true
    alias: gpt-5.1-2025-11-13
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: gpt-5.1
    mode: openai
    provider: openai
    enabled: true
    alias: gpt-5.1
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: gpt-5.2-2025-12-11
    mode: openai
    provider: openai
    enabled: true
    alias: gpt-5.2-2025-12-11
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: gpt-5.2
    mode: openai
    provider: openai
    enabled: true
    alias: gpt-5.2
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: gpt-5.2-chat-latest
    mode: openai
    provider: openai
    enabled: true
    alias: gpt-5.2-chat-latest
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: gpt-5.3-chat-latest
    mode: openai
    provider: openai
    enabled: true
    alias: gpt-5.3-chat-latest
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: gpt-5.4-2026-03-05
    mode: openai
    provider: openai
    enabled: true
    alias: gpt-5.4-2026-03-05
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: gpt-5.4
    mode: openai
    provider: openai
    enabled: true
    alias: gpt-5.4
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: gpt-5.4-nano
    mode: openai
    provider: openai
    enabled: true
    alias: gpt-5.4-nano
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: gpt-5.4-mini
    mode: openai
    provider: openai
    enabled: true
    alias: gpt-5.4-mini
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: gpt-5.5
    mode: openai
    provider: openai
    enabled: true
    alias: gpt-5.5
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: llm
    name: gpt-5.5-2026-04-23
    mode: openai
    provider: openai
    enabled: true
    alias: gpt-5.5-2026-04-23
    context_window: 128000
    prompt_style: chat
    tokenizer_mode: default
    support_image: 1
    support_audio: 0
    api_type: chat_completions
    support_tools: true
    support_reasoning: true
    tags: []
  - type: embedding
    name: text-embedding-ada-002
    mode: openai
    provider: openai
    enabled: true
    alias: text-embedding-ada-002
    context_window: 512
    embed_dim: 1536
    embedding_batch_size: 8
    tags: []
  - type: embedding
    name: text-embedding-3-small
    mode: openai
    provider: openai
    enabled: true
    alias: text-embedding-3-small
    context_window: 512
    embed_dim: 1536
    embedding_batch_size: 8
    tags: []
  - type: embedding
    name: text-embedding-3-large
    mode: openai
    provider: openai
    enabled: true
    alias: text-embedding-3-large
    context_window: 512
    embed_dim: 3072
    embedding_batch_size: 8
    tags: []
vectorstore:
  embed_dim: 1536
