server:
  env_name: ${APP_ENV:mock}

# This configuration allows you to use hardware acceleration for creating embeddings while avoiding loading the full LLM into (video) memory.
llm:
  mode: mock

embedding:
  mode: local