"""update department model

Revision ID: 36beb9b73c64
Revises: 0aeaf9df35a6
Create Date: 2024-02-21 15:12:07.840057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36beb9b73c64'
down_revision: Union[str, None] = '0aeaf9df35a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('total_users', sa.Integer(), nullable=True))
    op.add_column('departments', sa.Column('total_documents', sa.Integer(), nullable=True))
    # op.create_unique_constraint('unique_user_role', 'user_roles', ['user_id', 'role_id', 'company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('unique_user_role', 'user_roles', type_='unique')
    op.drop_column('departments', 'total_documents')
    op.drop_column('departments', 'total_users')
    # ### end Alembic commands ###
