"""Updated audit log

Revision ID: 62c1a29320fc
Revises: b526c0676007
Create Date: 2024-02-24 17:27:33.407895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62c1a29320fc'
down_revision: Union[str, None] = 'b526c0676007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('audit', 'model',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('audit', 'action',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('audit', 'url')
    op.drop_column('audit', 'model_id')
    # op.create_unique_constraint('unique_user_role', 'user_roles', ['user_id', 'role_id', 'company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('unique_user_role', 'user_roles', type_='unique')
    op.add_column('audit', sa.Column('model_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('audit', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('audit', 'action',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('audit', 'model',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('audit', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
