"""Add Subscription and Company model:


Revision ID: 65688535c5a5
Revises: cba9e6e394ca
Create Date: 2024-01-17 15:45:28.636265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65688535c5a5'
down_revision: Union[str, None] = 'cba9e6e394ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
