"""Created a relationships based on company

Revision ID: 6f93f0d1defb
Revises: 6f3cc13e1339
Create Date: 2024-01-20 15:46:13.093101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f93f0d1defb'
down_revision: Union[str, None] = '6f3cc13e1339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_roles', sa.Column('company_id', sa.Integer(), nullable=True))
    # op.create_unique_constraint('unique_user_role', 'user_roles', ['user_id', 'role_id', 'company_id'])
    op.create_foreign_key(None, 'user_roles', 'companies', ['company_id'], ['id'])
    op.add_column('users', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'company_id')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    # op.drop_constraint('unique_user_role', 'user_roles', type_='unique')
    op.drop_column('user_roles', 'company_id')
    # ### end Alembic commands ###
