"""Audit log update

Revision ID: b526c0676007
Revises: eb0a7f182c75
Create Date: 2024-02-24 12:00:11.632187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b526c0676007'
down_revision: Union[str, None] = 'eb0a7f182c75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('audit', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('audit', sa.Column('model', sa.String(), nullable=True))
    op.add_column('audit', sa.Column('model_id', sa.Integer(), nullable=True))
    op.add_column('audit', sa.Column('action', sa.String(), nullable=True))
    op.add_column('audit', sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_foreign_key(None, 'audit', 'users', ['user_id'], ['id'])
    op.drop_column('audit', 'headers')
    op.drop_column('audit', 'response')
    op.drop_column('audit', 'method')
    # op.create_unique_constraint('unique_user_role', 'user_roles', ['user_id', 'role_id', 'company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('unique_user_role', 'user_roles', type_='unique')
    op.add_column('audit', sa.Column('method', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('audit', sa.Column('response', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('audit', sa.Column('headers', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'audit', type_='foreignkey')
    op.drop_column('audit', 'details')
    op.drop_column('audit', 'action')
    op.drop_column('audit', 'model_id')
    op.drop_column('audit', 'model')
    op.drop_column('audit', 'user_id')
    op.drop_column('audit', 'timestamp')
    # ### end Alembic commands ###
