"""added password expiry

Revision ID: b7b23e5d5214
Revises: 62c1a29320fc
Create Date: 2024-02-24 19:47:49.069873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7b23e5d5214'
down_revision: Union[str, None] = '62c1a29320fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('unique_user_role', 'user_roles', ['user_id', 'role_id', 'company_id'])
    op.add_column('users', sa.Column('password_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_created')
    # op.drop_constraint('unique_user_role', 'user_roles', type_='unique')
    # ### end Alembic commands ###
