"""Documents association with multiple departments

Revision ID: f2978211af18
Revises: caa694775d4e
Create Date: 2024-03-06 16:43:16.492578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2978211af18'
down_revision: Union[str, None] = 'caa694775d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_department_association',
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], )
    )
    op.drop_constraint('document_department_id_fkey', 'document', type_='foreignkey')
    op.drop_column('document', 'department_id')
    # op.create_unique_constraint('unique_user_role', 'user_roles', ['user_id', 'role_id', 'company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('unique_user_role', 'user_roles', type_='unique')
    op.add_column('document', sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('document_department_id_fkey', 'document', 'departments', ['department_id'], ['id'])
    op.drop_table('document_department_association')
    # ### end Alembic commands ###
