name: deploy preview docs

on:
  pull_request_target:
    branches:
      - main
    paths:
      - "fern/**"

jobs:
  preview-docs:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Install Fern
        run: npm install -g fern-api@0.31.17

      - name: Generate Documentation Preview with Fern
        id: generate_docs
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: |
          fern generate --docs --preview --log-level debug | tee /tmp/fern-output.txt
          preview_url=$(grep -oP '(?<=Published docs to )https://[^\s]*' /tmp/fern-output.txt || true)
          echo "preview_url=$preview_url" >> "$GITHUB_OUTPUT"
      - name: Comment PR with URL using github-actions bot
        uses: actions/github-script@v9
        if: ${{ steps.generate_docs.outputs.preview_url }}
        with:
          script: |
            const preview_url = '${{ steps.generate_docs.outputs.preview_url }}';
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Published docs preview URL: ${preview_url}`
            })
